### ISSUE TITLE
There is no OpenCV implementations

### ISSUE THREAD

**Issue by adam-the-student** [adam-the-student/MOI2023-2024CenterStage#1]
Hey team, there is no implementations for opencv!

**Comment by adam-the-student** [comment]
I think i fixed this 

0c44e54f966f950e2ecead3778788cfc723d194e

**Comment by Caffeiphile** [comment]
Adam did not fix it, he just added the comment // HI IM ADAM

I have actually fixed it.


f4a22b6870cf814bb6c960d2842a7e83bca13242

**Comment by adam-the-student** [comment]
Amazing!
